sudo: false
language: python
env:
  - build=0
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - conda update --yes conda
  - conda info -a
install:
  - wget https://data.qiime2.org/distro/core/qiime2-2021.4-py38-linux-conda.yml
  - conda env create -q -n test-env --file qiime2-2021.4-py38-linux-conda.yml
  - conda install --yes -n test-env --file ci/conda_requirements.txt -c conda-forge
  - source activate test-env
  - conda install --yes flake8 nose coveralls
  - pip install -e .
  - qiime dev refresh-cache
script:
  - source activate test-env
  - flake8 q2_umap setup.py
  - nosetests -v q2_umap --with-coverage --cover-package=q2_umap
  - qiime umap --help
after_success:
  - coveralls
