name: q2-umap CI

on: [ push, pull_request ]

jobs:
  lint:
    name: Lint the code base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: flake8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install dependencies
        run: python -m pip install --upgrade pip
      - name: lint
        run: |
          pip install -q flake8
          flake8
  build-and-test:
    needs: lint
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.8
      - name: Install dependencies for linux
        if: matrix.os == 'ubuntu-latest'
        shell: bash -l {0}
        run: |
          conda create -n test-q2-umap
          conda activate test-q2-umap
          wget https://data.qiime2.org/distro/core/qiime2-2021.4-py38-linux-conda.yml
          conda env create -q -n test-env --file qiime2-2021.4-py38-linux-conda.yml
          conda install --yes -n test-env --file ci/conda_requirements.txt -c conda-forge
          source activate test-env
          conda install --yes flake8 nose coveralls
          pip install -e .
          qiime dev refresh-cache
      - name: Install dependencies for mac
        if: matrix.os == 'macos-latest'
        shell: bash -l {0}
        run: |
          conda create -n test-q2-umap
          conda activate test-q2-umap
          wget https://data.qiime2.org/distro/core/qiime2-2021.4-py38-osx-conda.yml
          conda env create -n qiime2-2021.4 --file qiime2-2021.4-py38-osx-conda.yml
          conda install --yes -n test-env --file ci/conda_requirements.txt -c conda-forge
          source activate test-env
          conda install --yes flake8 nose coveralls
          pip install -e .
          qiime dev refresh-cache
      - name: Tests
        shell: bash -l {0}
        run: |
          conda activate test-q2-umap
          nosetests